# Generated by Django 4.2.11 on 2024-03-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_post_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Categories'},
        ),
    ]
