# Generated by Django 4.2.11 on 2024-03-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',)},
        ),
    ]
